Changes made to mesh.h to create a virtual function to compute bin volume for spherical and cartesian geometry.
mphowardlab/flyft pull request #34
Opened 2022-12-08 22:26 UTC by mayukh33

2023-01-18 17:56 UTC, mphoward requested changes
Good start! Here are some suggestions. When you are ready, ping me on Slack for ideas for next steps to take.

2023-01-18 17:56 UTC, mphoward commented on include/flyft/mesh.h
> +
Try not to add extra white space if you can avoid it. We will use `clang-format` and `pre-commit` eventually to get rid of this, though, so I'm not going to worry too much about it now.

2023-01-18 17:56 UTC, mphoward commented on src/cartesian_mesh.cc
> +#include <cmath>
No need to use this header here
```suggestion
```

2023-01-18 17:56 UTC, mphoward commented on src/cartesian_mesh.cc
> +    return step_;
Perfect! I think we should start adding the cross-sectional area of the `CartesianMesh` in so that this is a true volume. However, I don't want to make too many changes at once so for now...

Can you add a private member variable to `CartesianMesh` called like `area_` or `cross_area_` (whatever you prefer), give it a default value of `1.0` in the constructor, then use it here like:
```suggestion
    return area_*step_;
```

2023-01-23 20:39 UTC, mphoward commented on src/cartesian_mesh.cc
> +    : Mesh(L,shape), area_(1.0)
```suggestion
    : CartesianMesh(L,shape,0)
```

2023-01-23 20:39 UTC, mphoward commented on src/cartesian_mesh.cc
> +    : Mesh(L,shape,origin)
```suggestion
    : Mesh(L,shape,origin), area_(1.0)
```

2023-01-23 20:39 UTC, mphoward commented on src/cartesian_mesh.cc
> +    : Mesh(shape,step,0)
```suggestion
    : CartesianMesh(shape,step,0)
```

2023-01-23 20:39 UTC, mphoward commented on src/cartesian_mesh.cc
> +    : Mesh(shape,step,origin)
```suggestion
    : Mesh(shape,step,origin), area_(1.0)
```

2023-02-01 15:37 UTC, mphoward requested changes
Good work! I had some suggestions for how we might reduce a little code duplication (and effort to make changes in future) by making the volume / surface integrals over a site be methods of the mesh. Could you try implementing these next?

2023-02-01 15:37 UTC, mphoward commented on src/boublik_hard_sphere_functional.cc
> +            energy = mesh->step()*rho*eta*(4.-3.*eta)/vf_2;
Should this be volume?

2023-02-01 15:37 UTC, mphoward commented on src/crank_nicolson_integrator.cc
> +                const double next_rate = (next_j(idx)-next_j(idx+1))/mesh->step();
This looks like it needs to be modified similarly as above, no?

Should we consider adding a method to the `Mesh` that will do the surface integral over a site to reduce code duplication? Something like this might be nice to give two different ways to write this:
```
double integrateSurface(int idx, double j_lo, double j_hi) const
    {
    return area(idx)*j_lo - area(idx+1)*j_hi;
    }
double integrateSurface(int idx, const DataView<double>& j) const
    {
    return integrateSurface(idx, j(idx), j(idx+1));
    }
```
You could then use it like:
```
const double next_rate = mesh->integrateSurface(idx, next_j)/mesh->volume(idx);
```

We could add a similar `integrateVolume` too, if we wanted to:
```
double integrateVolume(int idx, double f) const
    {
    return volume(idx)*f;
    }
double integrateVolume(int idx, const DataView<double>& f) const
    {
    return integrateVolume(idx, f(idx));
    }
```

This would match nicely when you went to implement the `gradient` method, which would be virtual.

2023-02-01 15:37 UTC, mphoward commented on src/explicit_euler_integrator.cc
> +            const auto rate = (mesh->area(idx)/mesh->volume(idx))*j(idx)-(mesh->area(idx+1)/mesh->volume(idx))*j(idx+1);
Revise as suggested above.

2023-02-01 15:37 UTC, mphoward commented on src/external_potential.cc
> +                    value_ += mesh->volume(idx)*rho*V;
With the integration method, this would look like:
```
value_ += mesh->integrateVolume(idx, rho*V);
```

2023-02-01 15:37 UTC, mphoward commented on src/grand_potential.cc
> +                    constraint_value -= mesh->volume(idx)*mu_bulk*rho(idx);
But this would look like:
```suggestion
                    constraint_value -= mu_bulk*mesh->integrateVolume(idx, rho);
```

2023-02-02 16:23 UTC, mphoward requested changes
Looks like you implemented the integrate methods correctly, but you missed quite a few spots applying them in the code. I think I got them all, so please apply these changes and then double check that there aren't any spots I missed!

2023-02-02 16:23 UTC, mphoward commented on include/flyft/mesh.h
> +#include "data_view.h"
You need to include flyft headers with the `flyft/` prefix:
```suggestion
#include "flyft/data_view.h"

#include <memory>
```
Also, headers should come in the following order:
1. This project
2. External libraries
3. Standard library
Separate each group with a line break.

2023-02-02 16:23 UTC, mphoward commented on include/flyft/mesh.h
> +        double integrateVolume(int idx, const DataView<double>& f) const;
For readability, group overloaded functions together
```suggestion
        double integrateSurface(int idx, double j_lo, double j_hi) const;
        double integrateSurface(int idx, const DataView<double>& j) const;
        
        double integrateVolume(int idx, double f) const;
        double integrateVolume(int idx, const DataView<double>& f) const;
```

2023-02-02 16:23 UTC, mphoward commented on src/boublik_hard_sphere_functional.cc
> +            energy = mesh->volume(idx)*(6./M_PI)*((xi2_3/xi3_2-xi[0])*logvf + 3.*xi[1]*xi[2]/vf + xi2_3/(xi[3]*vf_2));
```suggestion
            energy = mesh->integrateVolume(idx, (6./M_PI)*((xi2_3/xi3_2-xi[0])*logvf + 3.*xi[1]*xi[2]/vf + xi2_3/(xi[3]*vf_2));
```

2023-02-02 16:23 UTC, mphoward commented on src/boublik_hard_sphere_functional.cc
> +            energy = mesh->volume(idx)*rho*eta*(4.-3.*eta)/vf_2;
```suggestion
            energy = mesh->integrateVolume(idx, rho*eta*(4.-3.*eta)/vf_2);
```

2023-02-02 16:23 UTC, mphoward commented on src/crank_nicolson_integrator.cc
> +                const double next_rate = (next_j(idx)-next_j(idx+1))/mesh->step();
Shouldn't this be:
```suggestion
                const double next_rate = mesh->integrateSurface(idx, next_j)/mesh->volume(idx);
```

2023-02-02 16:23 UTC, mphoward commented on src/explicit_euler_integrator.cc
> +            const auto rate = mesh->integrateSurface(idx,j(idx),j(idx+1))/mesh->volume(idx);
Since `j` is a DataView, you should be able to use that overload
```suggestion
            const auto rate = mesh->integrateSurface(idx, j))/mesh->volume(idx);
```

2023-02-02 16:23 UTC, mphoward commented on src/grand_potential.cc
> +                    constraint_value -= mu_bulk*mesh->integrateVolume(idx,rho(idx));
Same here, `rho` is a `DataView` so that overload should work:
```suggestion
                    constraint_value -= mu_bulk*mesh->integrateVolume(idx, rho);
```

2023-02-02 16:23 UTC, mphoward commented on src/ideal_gas_functional.cc
> +            energy = mesh->volume(idx)*rho*(d(idx)-1.);
```suggestion
            energy = mesh->integrateVolume(idx, rho*(d(idx)-1.));
```

2023-02-02 16:23 UTC, mphoward commented on src/implicit_euler_integrator.cc
> +                const double next_rate = mesh->integrateSurface(idx,next_j(idx),next_j(idx+1))/mesh->volume(idx);
```suggestion
                const double next_rate = mesh->integrateSurface(idx, next_j)/mesh->volume(idx);
```

2023-02-02 16:23 UTC, mphoward commented on src/picard_iteration.cc
> +                    sum += mesh->integrateVolume(idx, rho(idx));
```suggestion
                    sum += mesh->integrateVolume(idx, rho);
```

2023-02-02 16:23 UTC, mphoward commented on src/rosenfeld_fmt.cc
> +                value_ += mesh->integrateVolume(idx, phi(idx));
```suggestion
                value_ += mesh->integrateVolume(idx, phi);
```

2023-02-02 16:23 UTC, mphoward commented on src/virial_expansion.cc
> +        value += mesh->volume(idx)*(factor*Bij*rhoi*rhoj);
```suggestion
        value += mesh->integrateVolume(idx, factor*Bij*rhoi*rhoj);
```

2023-02-13 21:04 UTC, mphoward requested changes
Looks good! A couple small things I noticed.

2023-02-13 21:04 UTC, mphoward commented on include/flyft/mesh.h
> +        double linearInterpolate(int idx, double rho_lo, double rho_hi) const;
I would rather call these `f` than `rho`, as I think it is more readable. Also, I would just call these `interpolate` so that it gives deriving classes the freedom to override the style of interpolation with whatever it thinks is best. For example:
```
double interpolate(int idx, double f_lo, double f_hi) const;
```

2023-02-13 21:04 UTC, mphoward commented on src/brownian_diffusive_flux.cc
> +        auto rho_avg = mesh->linearInterpolate(idx,rho);
This would look like:
```suggestion
        auto rho_avg = mesh->interpolate(idx,rho);
```

2023-02-13 21:04 UTC, mphoward commented on src/mesh.cc
> +    return origin_+static_cast<double>(i)*step_;
Perfect!

2023-02-13 21:04 UTC, mphoward commented on src/spherical_mesh.cc
> +    if(idx == 0){
I think you need an extra check here that `origin_ == 0.`, as this condition will be met on multiple domains:
```
if (idx == 0 && origin_ == 0.)
```
Alternatively, you can use the lower bound method that you added, at the expense of an extra multiplication operation. Hence, I would probably favor this version.

2023-02-17 23:03 UTC, mphoward requested changes
Looks good! Here are a couple small things. Did the code compile?

2023-02-17 23:03 UTC, mphoward commented on python/flyft/_flyft/spherical_mesh.cc
> +        .def(py::init<int,double,double>())
Is this the only constructor of the `SphericalMesh`, or are there others?

2023-02-17 23:03 UTC, mphoward commented on python/flyft/_flyft/state.cc
> +        .def(py::init<std::shared_ptr<ParallelMesh>, std::vector<std::string>&>())
I think this should be const?
```suggestion
        .def(py::init<std::shared_ptr<ParallelMesh>, const std::vector<std::string>&>())
```

2023-02-17 23:03 UTC, mphoward commented on python/flyft/_flyft/state.cc
> +        .def(py::init<const State&>())
Why was this added? We don't want to expose a copy constructor.
```suggestion
```

2023-02-18 00:01 UTC, mayukh33 commented on python/flyft/_flyft/spherical_mesh.cc
> +        .def(py::init<int,double,double>())
The spherical mesh did not have the other constructors. I added them now. The code is compiling!

2023-02-21 19:19 UTC, mphoward requested changes
Looks great! A couple small comments to resolve now, then we will move onto the pure Python code!

2023-02-21 19:19 UTC, mphoward commented on include/flyft/spherical_mesh.h
> +        SphericalMesh(double L, int shape, double origin);
Use R rather than L, since this is a sphere?
```suggestion
        SphericalMesh(double R, int shape);
        SphericalMesh(double R, int shape, double origin);  
```

2023-02-21 19:19 UTC, mphoward commented on src/spherical_mesh.cc
> +SphericalMesh::SphericalMesh(double L, int shape)
Apply the rename to R here.

2023-02-21 19:19 UTC, mphoward commented on python/flyft/_flyft/_flyft.cc
> +void bindCartesianMesh(py::module_&);
You need to make sure to add `cartesian_mesh.cc` and `spherical_mesh.cc` to `python/flyft/CMakeLists.txt` or they will not be compiled.

2023-02-21 19:19 UTC, mphoward commented on include/flyft/mesh.h
> +        double lower_bound(int i) const;
Now that these are called `lower_bound` and `upper_bound` (which I like alot!), would it make sense to rename `coordinate` to `center`? Then it would be clearer what this quantity represents.

2023-02-22 00:15 UTC, mayukh33 commented on include/flyft/mesh.h
> +        double lower_bound(int i) const;
That makes sense. I will make that change.

2023-03-01 17:20 UTC, mphoward commented on python/flyft/state.py
> +        return self._center
We currently pluralize anything that's an array, so this should be:
```suggestion
    def centers(self):
        if not hasattr(self, '_centers'):
            self._centers = np.array([self._self.center(i) for i in range(self.shape)])
        return self._centers
```

2023-03-01 17:25 UTC, mphoward commented on python/flyft/state.py
> +        Mesh.__init__(self,R,shape)
Do the same here as for `CartesianMesh`

2023-03-01 17:28 UTC, mphoward commented on python/flyft/state.py
> +
You should only call the constructor once, and it is done correctly below. Remove this.
```suggestion
```

2023-03-01 17:28 UTC, mphoward commented on python/flyft/state.py
> +    def __init__(self, mesh, communicator=None):
The `State` constructor needs a `ParallelMesh` and the `types`, but not the `communicator`:
```suggestion
    def __init__(self, mesh, types):
```

2023-03-01 17:29 UTC, mphoward commented on python/flyft/state.py
> +        communicator = Communicator()
Don't need this either, not sure why it is here.
```suggestion
```

2023-03-01 17:29 UTC, mphoward commented on python/flyft/state.py
> +            super().__init__(mesh,_flyft.VectorString(types))
You are only going to need this constructor now. Remove the `if-else`, and only keep this branch

2023-03-02 21:36 UTC, mphoward requested changes

2023-03-02 21:36 UTC, mphoward commented on python/flyft/state.py
> +            self._centers = np.array([self._self.centers(i) for i in range(self.shape)])
This method is not plural, it will crash if you actually run code with it:
```suggestion
            self._centers = np.array([self._self.center(i) for i in range(self.shape)])
```

2023-03-02 21:36 UTC, mphoward commented on python/flyft/state.py
> +        super().__init__(L,shape,area)
You still need to delete the `__init__` method for the `Mesh` above, or I suspect this will not work.

2023-03-02 21:36 UTC, mphoward commented on python/flyft/state.py
> +        super().__init__(mesh,_flyft.VectorString(types))
This was in the right spot below because it needs to come after `types` is cast to a tuple. Please put it back down there, you only need to remove the `if-else` logic and keep this line.

2023-03-12 15:35 UTC, mphoward reviewed
These changes all look good, onto the unit tests!

2023-03-17 21:25 UTC, mphoward commented on python/flyft/state.py
> +        super().__init__(mesh)
You shouldn't have removed the communicator here, that might be causing your error:
```suggestion
        super().__init__(mesh, communicator)
```

2023-03-27 16:34 UTC, mphoward commented on src/cartesian_mesh.cc
> +    : CartesianMesh(shape,step,0,area)
```suggestion
    : CartesianMesh(shape,step,area,0)
```

2023-03-27 16:38 UTC, mphoward commented on src/cartesian_mesh.cc
> +    return std::shared_ptr<Mesh>(new CartesianMesh(end-start,step_,lower_bound(start)));
```suggestion
    return std::shared_ptr<Mesh>(new CartesianMesh(end-start,step_,area_,lower_bound(start)));
```

2023-03-29 17:10 UTC, mphoward requested changes

2023-03-29 17:10 UTC, mphoward commented on src/picard_iteration.cc
> +                    sum += mesh->integrateVolume(idx, rho_tmp);
Good find! Was a test failing because of this?

2023-03-29 17:10 UTC, mphoward commented on python/tests/test_explicit_euler_integrator.py
> +    mesh = flyft.state.ParallelMesh(flyft.state.CartesianMesh(2.,100,1))
Why this change?

2023-03-29 17:22 UTC, mayukh33 commented on src/picard_iteration.cc
> +                    sum += mesh->integrateVolume(idx, rho_tmp);
Yes! The picard iteration test was failing

2023-04-03 19:09 UTC, mphoward commented on include/flyft/state.h
> +        State(std::shared_ptr<ParallelMesh> mesh, const std::vector<std::string>& types);
Would it make sense to go to an intermediate solution like this?
```c++
State(std::shared_ptr<Mesh> mesh, const std::string& type);
State(std::shared_ptr<Mesh> mesh, const std::vector<std::string>& type);
State(std::shared_ptr<Mesh> mesh, const std::string& type, std::shared_ptr<Communicator> comm);
State(std::shared_ptr<Mesh> mesh, const std::vector<std::string>& type, std::shared_ptr<Communicator> comm);
```

2023-04-12 21:56 UTC, mphoward requested changes

2023-04-12 21:56 UTC, mphoward commented on python/flyft/_flyft/mesh.cc
> +        PYBIND11_OVERLOAD_PURE_NAME(double, Mesh, "total_volume", volume, );
How about we just call this `volume` (and remove the extra `,`:
```suggestion
        PYBIND11_OVERLOAD_PURE(double, Mesh, volume);
```

2023-04-12 21:56 UTC, mphoward commented on python/flyft/_flyft/mesh.cc
> +        .def("total_volume",py::overload_cast<>(&Mesh::volume, py::const_))
We could decide to make this one a property and read only, it would make sense. I think this would work:
```suggestion
        .def_property_readonly("volume", py::overload_cast<>(&Mesh::volume, py::const_))
```

2023-04-12 21:56 UTC, mphoward commented on python/flyft/state.py
> +            v = self._self.total_volume()
If changes above work, this would be:
```suggestion
            v = self._self.volume
```

2023-04-12 21:56 UTC, mphoward commented on python/flyft/state.py
> +    def volume(self, bin = None):
```suggestion
    def volume(self, bin=None):
```

2023-04-12 21:56 UTC, mphoward commented on python/tests/conftest.py
> +    return mesh.volume()
This should not be a fixture
```suggestion
```

2023-04-12 21:56 UTC, mphoward commented on python/tests/test_boublik_hard_sphere.py
> +def test_compute(bmcsl,binary_state,volumes):
```suggestion
def test_compute(bmcsl,binary_state):
```

2023-04-12 21:56 UTC, mphoward commented on python/tests/test_boublik_hard_sphere.py
> +    assert bmcsl.value == pytest.approx(volumes*fex_cs(eta,d))
Just call the volume method:
```suggestion
    assert bmcsl.value == pytest.approx(state.mesh.full.volume()*fex_cs(eta,d))
```

2023-04-12 21:56 UTC, mphoward commented on python/tests/test_boublik_hard_sphere.py
> +    assert bmcsl.value == pytest.approx(volumes*fex_cs(eta,d))
Please correct in all files, I'm going to stop marking these.

2023-04-12 21:56 UTC, mphoward commented on python/tests/test_crank_nicolson_integrator.py
> +    # grand.external = linear
Don't comment stuff out from failing tests, or you will forget it needs to be fixed:
```suggestion
    linear.set_line('A', x=0., y=0., slope=0.25)
    grand.external = linear
```

2023-04-12 21:56 UTC, mphoward commented on python/tests/test_mesh.py
> +    return flyft.state.SphericalMesh(10.0,20)
Shouldn't this fixture be deleted now, and it will run on both defined in `conftest.py`?

2023-04-12 21:56 UTC, mphoward commented on python/tests/test_mesh.py
> +
This looks like it belongs in a separate test for the `volume` method. You can define one test for the `cartesian_mesh` fixture and one for the `spherical_mesh` fixture so you can use different values for each

2023-04-12 21:56 UTC, mphoward commented on src/spherical_mesh.cc
> +    return (4.*M_PI/3.)*(L_*L_*L_);
This will fail if the domain is shifted (`origin_ != 0`). This should always work, I think:
```suggestion
    const double rlo = lower_bound(0);
    const double rhi = upper_bound(shape_-1);
    return (4.*M_PI/3.)*(rhi*rhi*rhi - rlo*rlo*rlo);
```

2023-04-12 22:05 UTC, mayukh33 commented on python/tests/test_mesh.py
> +    return flyft.state.SphericalMesh(10.0,20)
Yes! I made the change after pushing it on github 😅

2023-04-12 22:06 UTC, mayukh33 commented on python/tests/test_crank_nicolson_integrator.py
> +    # grand.external = linear
I forgot to uncomment this one! Thank you for finding it!

2023-04-14 16:07 UTC, mphoward requested changes

2023-04-14 16:07 UTC, mphoward commented on python/tests/test_brownian_diffusive_flux.py
> +def test_excess(grand,state_grand,ig,bd):
Same idea for the testing here.

2023-04-14 16:07 UTC, mphoward commented on python/tests/test_brownian_diffusive_flux.py
> +    print(grand.external)
```suggestion
```

2023-04-14 16:07 UTC, mphoward commented on python/tests/test_crank_nicolson_integrator.py
> +def test_sine(adapt,cn,state_sine):
Same comment here, it's OK if you just want it to run on `CartesianMesh`.

2023-04-21 14:32 UTC, mphoward approved these changes
Additional work is still needed, but we are merging into a staging branch to keep the PR manageable. Good job!

2023-04-21 14:33 UTC, merged