Rosenfeld FMT for spherical geometry
mphowardlab/flyft pull request #36
Opened 2023-04-20 15:56 UTC by mayukh33

2023-05-24 18:58 UTC, mphoward reviewed
Overall, I think this is in good shape! I noted some spots we should work on. Let's make a plan for who will implement these steps. Then, I think we are ready to test this code out.

We do still need to iron out the MPI communication for the spherical geometry, but that shouldn't get in the way of testing provided we pad the domain with enough zeros.

2023-05-24 18:58 UTC, mphoward commented on src/rosenfeld_fmt.cc
> +                // TODO: there is a missing term for nv1 and nv2
Remove TODO items when they are completed
```suggestion
```

2023-05-24 18:58 UTC, mphoward commented on src/rosenfeld_fmt.cc
> +                dphi_dnv2k_w3k(idx) = -dphi_dnv2k(idx)*w3;
Just want to check there should be a minus sign here because we are flipping the whole order of convolution (before we break it into two integrals) because w3 itself is even. I think it should be here, and we should add a comment as to why

2023-05-24 18:58 UTC, mphoward commented on src/rosenfeld_fmt.cc
> +    setupField(tmp_dF_dnv1_w3);
It might be helpful to denote the second term like `tmp_dF_dnv1_2` rather than `tmp_dF_dnv1_w3` to make clear it is the terms of the derivative?

2023-05-24 18:58 UTC, mphoward commented on src/rosenfeld_fmt.cc
> +                dF_dnv1(idx) = dF_dnv1_w3(idx)/(r*r)+dF_dnv1(idx);
Let's add a comment and use `+=` so it's obvious what this is doing
```suggestion
                // consolidate second term with first
                dF_dnv2(idx) += dF_dnv2_w3(idx)/(r*r);
                dF_dnv1(idx) += dF_dnv1_w3(idx)/(r*r);
```

2023-05-24 18:58 UTC, mphoward commented on src/rosenfeld_fmt.cc
> +        if (mesh->lower_bound(0) < R)
I think I handled this correctly, but let's confirm that there is only one integral necessary here for the vector weighted terms. It is the last page of the notes. I think all we need to do is replace rho by dphi/dnv2.

2023-05-24 18:58 UTC, mphoward commented on src/rosenfeld_fmt.cc
> +void RosenfeldFMT::computeCartesianWeightedDensities(std::shared_ptr<State> state)
Usually we like to put functions in the order they appear in the header. Making a note that we should align the `cc` file and `h` file function order at the very end. (Don't do it now or it will make a big change set that is just moving lines.)

2023-05-24 18:58 UTC, mphoward commented on src/rosenfeld_fmt.cc
> +    for (const auto& t : state->getTypes())
Making a note that we should think through whether we keep doing the Cartesian weights in this special way, or if we should do it more like the spherical ones. The only advantage of doing this is to reduce the number of Fourier transforms when there are like 1 or 2 types, and to reduce the communication overhead in general.

2023-05-24 18:58 UTC, mphoward commented on src/rosenfeld_fmt.cc
> +    // TODO: we should only be alloc'ing these once, will fix later
Noting that this here should also be handled in the `tmp` allocation

2023-05-24 18:58 UTC, mphoward commented on src/rosenfeld_fmt.cc
> +            auto nv2k = nv2k_->view();
These are candidates to become `tmp` variables as well

2023-05-31 13:44 UTC, mphoward reviewed
You definitely have the right idea here! If the code continues to compile and run, this is exactly what I had in mind. Please take a look at the suggestions, then continue to address any comments that are simple fixes on this PR. Please resolve those from the Conversation tab as you do that (if they are trivial), or comment if you need to me to confirm they are done right.

2023-05-31 13:44 UTC, mphoward commented on src/rosenfeld_fmt.cc
> +    // TODO: cache allocation
Remove TODO comments as they are addressed
```suggestion
```

2023-05-31 13:44 UTC, mphoward commented on src/rosenfeld_fmt.cc
> +    // TODO: we should only be alloc'ing these once, will fix later
```suggestion
```

2023-05-31 13:44 UTC, mphoward commented on src/rosenfeld_fmt.cc
> +            auto nv2k = nv2k_->view();
These could use `tmp_complex_field_` rather than be member variables. You would want to delete the member variables.

2023-05-31 13:44 UTC, mphoward commented on src/rosenfeld_fmt.cc
> +    std::fill(nv2k_->view().begin(), nv2k_->view().end(), 0.);
Same here for Cartesian, these should probably be `tmp_complex_field_` rather than member variables.

Unlike `n0_`, `n1_`, etc., these do not have meaning outside of their use in convolution. Therefore, they are `tmp`.

2023-05-31 13:44 UTC, mphoward commented on src/rosenfeld_fmt.cc
> +    setupField(tmp_field_["nv2"]);
Are all 6 of these needed? It looks like only 3 are used below.

2023-05-31 17:07 UTC, mayukh33 commented on src/rosenfeld_fmt.cc
> +    std::fill(nv2k_->view().begin(), nv2k_->view().end(), 0.);
It makes sense. I will change them to `tmp` variables.

2023-06-22 20:48 UTC, mphoward requested changes
Overall this looks it should work! I had some suggestions, and one or two small issues of correctness. Please address those.

I didn't carefully check the integral formulas, so if you want to do that please let me know to have a look at this in a final review before merging..

2023-06-22 20:48 UTC, mphoward commented on src/mesh.cc
> +    return interpolate(x,f);
To confirm: this works and does not lead to infinite recursion?

2023-06-22 20:48 UTC, mphoward commented on src/rosenfeld_fmt.cc
> +
Even though `lower = 0`, you should still include it here in case you ever needed to change `lower` for some reason. This also makes the variable declaration more compact:
```suggestion
                // integral 1
                // we have found 100 points works well
                const int n = 100;
                double dr = (split-lower)/n;
                double x = lower;
```

2023-06-22 20:48 UTC, mphoward commented on src/rosenfeld_fmt.cc
> +                const auto upper = r+R;
I would be explicit about the type here:
```suggestion
                const double lower = 0.;
                const double split = R-r;
                const double upper = r+R;
```

2023-06-22 20:48 UTC, mphoward commented on src/rosenfeld_fmt.cc
> +
```suggestion
                // integral 2
                dr = (upper-split)/n;
                x = split;                
```

2023-06-22 20:48 UTC, mphoward commented on src/rosenfeld_fmt.cc
> +                    double dphi_dnv2_ig = mesh->interpolate(x, dphi_dnv2);
I would use `const auto` here, `const` since we know this will not change and `auto` since we want it to have the return type from `interpolate` (which will match the data type).
```suggestion
                    const auto dphi_dn0_ig = mesh->interpolate(x, dphi_dn0);
                    const auto dphi_dn1_ig = mesh->interpolate(x, dphi_dn1);
                    const auto dphi_dn2_ig = mesh->interpolate(x, dphi_dn2);
                    const auto dphi_dn3_ig = mesh->interpolate(x, dphi_dn3);
                    const auto dphi_dnv1_ig = mesh->interpolate(x, dphi_dnv1);
                    const auto dphi_dnv2_ig = mesh->interpolate(x, dphi_dnv2);
```

2023-06-22 20:48 UTC, mphoward commented on src/rosenfeld_fmt.cc
> +                dF_dn3(idx) = (dF_dn3_1+dF_dn3_2)*dr;
Don't these integrals have different step sizes? I would split this up: do `dF_dn3_1 *= dr;` after the first integral, then:
```suggestion
                dF_dn3(idx) = dF_dn3_1 + dF_dn3_2*dr; 
```
here.

2023-06-22 20:48 UTC, mphoward commented on src/rosenfeld_fmt.cc
> +                    nv2_ig_2 += factor * (M_PI/(r*r)) * (rho_ig * x  * (R*R + r*r - x*x));
Can't these be acculumated directly?
```suggestion
                    n2(idx) += factor * (2.*M_PI*R/r) * rho_ig * x;
                    nv2(idx) += factor * (M_PI/(r*r)) * (rho_ig * x  * (R*R + r*r - x*x));
```

2023-06-22 20:48 UTC, mphoward commented on src/rosenfeld_fmt.cc
> +                dr = split/n;
```suggestion
                // integral 1
                const int n = 100;
                const double dr = (split-lower)/n;
                double x = lower;
```

2023-06-22 20:48 UTC, mphoward commented on src/rosenfeld_fmt.cc
> +                double nv2_ig_2 = 0;
```suggestion
                double n3_ig_1 = 0;
                double n3_ig_2 = 0; 
```

2023-06-22 20:48 UTC, mphoward commented on src/rosenfeld_fmt.cc
> +
As in the functional derivative, make sure to scale `n3_ig_1 *= dr;` here.

2023-06-22 20:48 UTC, mphoward commented on src/rosenfeld_fmt.cc
> +                nv2i(idx) = nv2_ig_2*dr;
```suggestion
                n3i(idx) = n3_ig_1 + n3_ig_2*dr;
                n2i(idx) *= dr;
                nv2i(idx) *= dr;
```

2023-06-22 20:48 UTC, mphoward commented on src/rosenfeld_fmt.cc
> +                std::cout<<mesh->center(idx)<<", "<<n3(idx)<<", "<<n2(idx) <<", "<<nv2(idx)<<std::endl;
Don't commit debug statements.
```suggestion
```

2023-06-22 21:52 UTC, mayukh33 commented on src/mesh.cc
> +    return interpolate(x,f);
Yes! It works!

2023-06-22 21:52 UTC, mayukh33 commented on src/mesh.cc
> +    return interpolate(x,f);
Yes! It works!

2023-07-12 19:29 UTC, mphoward commented on src/rosenfeld_fmt.cc
> +    for (const auto& t : state->getTypes())
Will not be handled in this PR.

2023-07-17 18:22 UTC, mphoward approved these changes
Some todo items (fix interpolation scheme and boundary conditions), will be handled in subsequent PRs!

2023-07-17 18:22 UTC, merged