Add quadratic parameter for spherical geometry
mphowardlab/flyft pull request #41
Opened 2023-09-18 18:52 UTC by mayukh33

2023-09-19 13:27 UTC, mphoward commented
This looks good, but maybe we should call this `SquareRootParameter` or something like that? To me, `QuadraticParameter` implies something like:
```
x(t) = t^2
```

2023-09-21 15:59 UTC, mayukh33 commented
There is a unit test for `LinearParameter`. I will add to that.

2023-09-22 20:14 UTC, mphoward requested changes
Thanks! This all looks good to me. Maybe one day we can refactor this so there is less duplication between parameters, but I am good with it for now.

Can you please address the two comments below, and then we can merge?

2023-09-22 20:14 UTC, mphoward commented on include/flyft/parameter.h
> +                value_ = sqrt(initial_*initial_+rate_*(time_-origin_));
The issue isn't actually if the time is negative, it's if the argument of the square root is negative. You should do like this:
```suggestion
                const double value_sq = initial_*initial_+rate_*(time_-origin_);
                if(value_sq < 0)
                    {
                    throw std::invalid_argument("Time makes argument of square root negative");
                    }
                value_ = std::sqrt(value_sq);
```
Note I'm also using `std::sqrt`.

2023-09-22 20:14 UTC, mphoward commented on python/tests/test_parameter.py
> +        squareroot(state)
You only expect a value error when you actually evaluate, so do like this:
```suggestion
    state.time = -1.0
    squareroot = flyft.parameter.SquareRootParameter(3.0, 1.0, 4.5)
    with pytest.raises(ValueError):
        squareroot(state)
```
Note also you should have a test where t is a valid (>= 0) time, but the square root cannot evaluate because the argument to the square root goes negative.

2023-09-27 15:47 UTC, mphoward approved these changes
Thank you! Could you confirm the one change I marked works and commit it? This is ready to merge after you do that.

2023-09-27 15:47 UTC, mphoward commented on python/tests/test_parameter.py
> +    squareroot = flyft.parameter.SquareRootParameter(1.0, 1.0, -3.0)
One small thing here to make it simpler (& also test the setter):
```suggestion

    state.time = 2.0
    squareroot.rate = -3.0
```

2023-09-27 22:44 UTC, merged