Add 3D Grid interpolation for rdf and mobility integral
mphowardlab/flyft pull request #48
Opened 2024-01-18 20:45 UTC by mayukh33

2024-01-19 15:00 UTC, mphoward requested changes

2024-01-19 15:00 UTC, mphoward commented on src/three_dimension_index.cc
> +    return i*j*k;
```suggestion
    return ni_*nj_*nk_;
```

2024-01-19 15:00 UTC, mphoward commented on src/three_dimension_index.cc
> +    ni_(ni), nj_(nj), nk_(nk)
```suggestion
ThreeDimensionIndex::ThreeDimensionIndex(int ni , int nj, int nk)
    : ni_(ni), nj_(nj), nk_(nk)
```

2024-01-19 15:00 UTC, mphoward commented on include/flyft/three_dimension_index.h
> +        int operator()(int i, int j, int k) const;
```suggestion

        int operator()(int i, int j, int k) const;

        int size() const;
```

2024-01-19 15:00 UTC, mphoward commented on include/flyft/three_dimension_index.h
> +    protected:
These can be private, we aren't likely to subclass this
```suggestion
    private:
```

2024-01-19 15:00 UTC, mphoward commented on include/flyft/three_dimension_index.h
> +        int i, j, k;
These are not member variables, they are arguments of the call operator
```suggestion
```

2024-01-26 02:53 UTC, mphoward requested changes
Thanks for taking a first stab at this. The interpolator definitely needs some more work. We can chat on Monday if you can't figure it out from these comments!

2024-01-26 02:53 UTC, mphoward commented on include/flyft/three_dimension_index.h
> +        int index_;
```suggestion
```

2024-01-26 02:53 UTC, mphoward commented on include/flyft/three_dimension_index.h
> +    protected:
This comment still applies

2024-01-26 02:53 UTC, mphoward commented on include/flyft/grid_interpolator.h
> +        GridInterpolator(std::string s,int ni, int nj, int nk, double dx, double dy, double dz);
I don't think you need all of these constructors since we are just hacking this together. If the file is going to have the bounds in it as the first 6 values, then do like this:
```suggestion
        GridInterpolator(const std::string& s);
```
FYI: We use the const and & for strings to make sure it is passed by const reference.

2024-01-26 02:53 UTC, mphoward commented on src/grid_interpolator.cc
> +    n_(ni, nj, nk), dx_(dx), dy_(dy), dz_(dz)
delete all of this
```suggestion
```

2024-01-26 02:53 UTC, mphoward commented on src/grid_interpolator.cc
> +            }
This is for sure not right, you are looping over every index in the data and assigning it value each time. So by the time this is done, the whole array will have been iterated n_.size() times, but every entry will be the last value!

It should be more like this:
```suggestion
        int idx = 0;
        while (indata >> value)
            {
            data_[idx++] = value;
            }
       if (idx != n_.size() || !indata.eof())
           {
           throw std::runtime_error("File did not have right number of elements.");
           }
```

2024-01-26 02:53 UTC, mphoward commented on src/grid_interpolator.cc
> +        {
I don't think this is the right way to open & read a file, as far as I remember. I would have done:
```suggestion
    std::ifstream indata(s);
    if (!indata)
        {
        throw std::runtime_error("Failed to open file");
        }
```
Simpler initialization, no while loop needed.

2024-01-26 02:53 UTC, mphoward commented on src/grid_interpolator.cc
> +    data_ = new double[n_.size()];
You will need to move this down, right after the file is opened, and read the 6 values in that you need like:
```
int nx, ny, nz;
indata >> nx >> ny >> nz >> dx_ >> dy_ >> dz_;
n_ = ThreeDimensionIndex(nx, ny, nz);
if (n_.size() == 0)
    {
    throw std::runtime_error("Grid has zero size");
    }
data _ = new double[n_.size()]

```

2024-01-26 02:53 UTC, mphoward commented on src/grid_interpolator.cc
> +    assert(bin_z >= 0 || bin_z < nk);
both of these need to be true at the same time:
```suggestion
    assert(bin_x >= 0 && bin_x < ni);
    assert(bin_y >= 0 && bin_y < nj);
    assert(bin_z >= 0 && bin_z < nk);
```

2024-01-26 02:53 UTC, mphoward commented on src/grid_interpolator.cc
> +GridInterpolator::~GridInterpolator()
Put destructors right after constructors.

2024-01-26 02:53 UTC, mphoward commented on src/m.dat
Delete this, it is research data.

2024-01-26 02:53 UTC, mphoward commented on src/rpy_diffusive_flux.cc
> +
Let's not worry about this for now either
```suggestion
```

2024-01-26 02:53 UTC, mphoward commented on include/flyft/three_dimension_index.h
> +        std::tuple<int, int, int> backmapping(int k) const;
This needs a better name for the function and its argument, but it's fine for now

2024-01-26 02:53 UTC, mphoward commented on src/three_dimension_index.cc
> +    int x =  (((k-z)/nk_)-y)/nj_;
Does this not work?
```suggestion
    const int z = k % nk_;
    const int y = (k / nk_) % nj_;
    const int x =  k / (n_j * nk_);
```

2024-01-26 18:14 UTC, mayukh33 commented on src/three_dimension_index.cc
> +    int x =  (((k-z)/nk_)-y)/nj_;
I tried an example hand calculation using (x,y,z) = (1, 2, 3) and (ni, nj,  nk) = (5, 5, 5), and the equations I have used work since `k-z` makes it divisible by nk while k would result in a value with decimals. I also tried with (x,y,z) = (3,1,2) with (6,6,6) and (8,4,6) grid size, and the equation I had worked for that as well.

2024-01-26 18:28 UTC, mphoward commented on src/three_dimension_index.cc
> +    int x =  (((k-z)/nk_)-y)/nj_;
That is probably true, but does what I wrote also work? It uses less arithmetic and I think achieves the same result because integer math drops remainders.

2024-01-26 18:31 UTC, mayukh33 commented on include/flyft/grid_interpolator.h
> +        GridInterpolator(std::string s,int ni, int nj, int nk, double dx, double dy, double dz);
I have tried to implement it without the constructors, but it gives me this error:
`no default constructor exists for class "flyft::ThreeDimensionIndex"C/C++(291)`, even though I give the constructor for the ThreeDimensionIndex later within the constructor.

2024-01-26 18:32 UTC, mayukh33 commented on src/three_dimension_index.cc
> +    int x =  (((k-z)/nk_)-y)/nj_;
Oh, I see! Let me check!

2024-01-26 18:32 UTC, mphoward commented on include/flyft/grid_interpolator.h
> +        GridInterpolator(std::string s,int ni, int nj, int nk, double dx, double dy, double dz);
You need to implement a default constructor (the constructor that takes no arguments) for the ThreeDimensionIndex then! Fill the dimensions and spacings with zeros, for example

2024-01-26 18:44 UTC, mayukh33 commented on src/three_dimension_index.cc
> +    int x =  (((k-z)/nk_)-y)/nj_;
Yes, it works! Sorry about that!

2024-01-26 19:03 UTC, mayukh33 commented on include/flyft/grid_interpolator.h
> +        GridInterpolator(std::string s,int ni, int nj, int nk, double dx, double dy, double dz);
Okay!

2024-01-26 20:48 UTC, mphoward requested changes
Looking better, here are some more suggestions!

2024-01-26 20:48 UTC, mphoward commented on include/flyft/grid_interpolator.h
> +        GridInterpolator();
Unless we need it, I wouldn't give this a default constructor. It doesn't make sense to initialize this without any data with the way it currently is setup.
```suggestion
```

2024-01-26 20:48 UTC, mphoward commented on include/flyft/grid_interpolator.h
> +        double* getData() const;
You no longer need to expose this data either.
```suggestion
```

2024-01-26 20:48 UTC, mphoward commented on include/flyft/grid_interpolator.h
> +#include <cmath>
This is the only header you need here from the standard library, right? Include the other stuff in the `.cc` file where it's used.
```suggestion
#include <string>
```

2024-01-26 20:48 UTC, mphoward commented on include/flyft/rpy_diffusive_flux.h
> +
Don't add unrelated changes in this PR, we will deal with the RPY stuff later.
```suggestion
```

2024-01-26 20:48 UTC, mphoward commented on include/flyft/three_dimension_index.h
> +        int nx_, ny_, nz_;
We declare member variables one at a time
```suggestion
        int nx_;
        int ny_;
        int nz_;
```

2024-01-26 20:48 UTC, mphoward commented on src/grid_interpolator.cc
> +    }
```suggestion
```

2024-01-26 20:48 UTC, mphoward commented on src/grid_interpolator.cc
> +    indata>>nx>>ny>>nz>>dx>>dy>>dz;
Use whitespace to make this more readable, and read directly into the member variables when it's possible.
```suggestion
    int nx, ny, nz;
    indata >> nx >> ny >> nz >> dx_ >> dy_ >> dz_;
```

2024-01-26 20:48 UTC, mphoward commented on src/grid_interpolator.cc
> +    double dx, dy, dz;
We put variables where we use them
```suggestion
```

2024-01-26 20:48 UTC, mphoward commented on src/grid_interpolator.cc
> +
Again, use whitespace to group concepts together. This is all related to making the indexer
```suggestion
```

2024-01-26 20:48 UTC, mphoward commented on src/grid_interpolator.cc
> +
Then this is all related to reading the data
```suggestion
```

2024-01-26 20:48 UTC, mphoward commented on src/grid_interpolator.cc
> +
```suggestion
```

2024-01-26 20:48 UTC, mphoward commented on src/grid_interpolator.cc
> +
One line of whitespace between functions in C++
```suggestion
```

2024-01-26 20:48 UTC, mphoward commented on src/grid_interpolator.cc
> +
No whitespace to start a function
```suggestion
```

2024-01-26 20:48 UTC, mphoward commented on src/grid_interpolator.cc
> +    assert(bin_z >= 0 && bin_z < nk);
If this is the only spot it's used, can you just take this in the tuple and then use get on it?
```suggestion
    const auto bounds = n_.getBounds();
    assert(bin_x >= 0 && bin_x < std::get<0>(bounds));
    assert(bin_y >= 0 && bin_y < std::get<1>(bounds));
    assert(bin_z >= 0 && bin_z < std::get<2>(bounds));
```

2024-01-26 20:48 UTC, mphoward commented on src/grid_interpolator.cc
> +    int bin_x = std::floor(x/dx_);
All these variables should be declared with `const` here and below, they are not modified.

2024-01-26 20:48 UTC, mphoward commented on src/grid_interpolator.cc
> +
```suggestion
```

2024-01-26 20:48 UTC, mphoward commented on src/rpy_diffusive_flux.cc
> +
Again, make sure these files aren't even showing up in your diff
```suggestion
```

2024-01-26 20:48 UTC, mphoward commented on src/three_dimension_index.cc
> +{
Where is the default constructor defined? It should be in this file, like:
```
ThreeDimensionIndex::ThreeDimensionIndex()
    : nx_(0), ny_(0), nz_(0)
    {}
```

2024-01-26 20:48 UTC, mphoward commented on src/three_dimension_index.cc
> +int ThreeDimensionIndex::operator()(int i, int j, int k) const
Remember to put functions in cc files in the same order they are declared in the header for readability

2024-01-26 20:48 UTC, mphoward commented on include/flyft/three_dimension_index.h
> +        std::tuple<int, int, int> backmapping(int k) const;
I suggest the following:
```suggestion
        std::tuple<int, int, int> asTuple(int idx) const;
```

2024-01-26 20:48 UTC, mphoward commented on src/three_dimension_index.cc
> +    const int z = k % (nz_);
Don't put parentheses around single variables
```suggestion
    const int z = k % nz_;
```

2024-01-26 22:05 UTC, mphoward requested changes

2024-01-26 22:05 UTC, mphoward commented on include/flyft/three_dimension_index.h
> +        std::tuple<int, int, int> asTuple(int k) const;
Rename this to `idx` everywhere. `k` is confusing because it seems like the z index.
```suggestion
        std::tuple<int, int, int> asTuple(int idx) const;
```

2024-01-26 22:05 UTC, mphoward commented on include/flyft/three_dimension_index.h
> +        int operator()(int i, int j, int k) const;
Swap the order of these, I would expect to see the call operator first since it's most important.

2024-01-26 22:05 UTC, mphoward commented on src/grid_interpolator.cc
> +
Make sure all these changes get implemented and resolve them.

2024-01-26 22:05 UTC, mphoward commented on src/grid_interpolator.cc
> +    assert(bin_x >= 0 && bin_x < std::get<0>(n_.getBounds()));
Do still store the bounds once, it is more readable. You just don't need to unpack it into 3 vars. Like so:
```suggestion
    const auto bounds = n_.getBounds();
    assert(bin_x >= 0 && bin_x < std::get<0>(bounds)));
```
apply to the next two lines as well.

2024-01-26 22:05 UTC, mphoward commented on src/rpy_diffusive_flux.cc
>      setup(grand,state);
Please put this line break back... the easier way to make sure you actually got rid of the old changes (which is how I think you accidentally deleted this line) would have been to use git to revert the file to the main branch. You can do that now.
```
git checkout main -- rpy_diffusive_flux.cc
```

2024-01-30 16:22 UTC, mphoward requested changes
This looks generally good! Here are a few small things left to address.

2024-01-30 19:38 UTC, mphoward requested changes

2024-01-30 19:38 UTC, mphoward commented on include/flyft/three_dimensional_index.h
> +#include <cmath>
Is this header needed here? You just have ints and tuples.

2024-01-30 19:38 UTC, mphoward commented on src/grid_interpolator.cc
> +    #endif
whitespace for readability
```suggestion

    #ifndef NDEBUG
    const auto bounds = n_.getBounds();
    assert(bin_x >= 0 && bin_x < std::get<0>(bounds));
    assert(bin_y >= 0 && bin_y < std::get<1>(bounds));
    assert(bin_z >= 0 && bin_z < std::get<2>(bounds));
    #endif

```

2024-01-30 19:38 UTC, mphoward commented on CMakeLists.txt
> +    set(CMAKE_BUILD_TYPE RelWithDebInfo CACHE STRING "Choose the type of build." FORCE)
revert

2024-01-30 20:39 UTC, mphoward approved these changes
Looks great, thanks!

2024-01-30 20:39 UTC, merged