Add grid Interpolation to RPY diffusive flux
mphowardlab/flyft pull request #49
Opened 2024-01-30 22:37 UTC by mayukh33

2024-01-31 14:24 UTC, mphoward commented on src/rpy_diffusive_flux.cc
> +    GridInterpolator g("/scratch2/mzk0148/projects/ddft_droplet/data/rdf_surrogate/m.dat");
You will want to construct and allocate this only once. The easiest way is to add a shared pointer to the class:
```
std::shared_ptr<GridInterpolator> m_mobility;
```
and then for now, you can make it in the constructor:
```
m_mobility = std::make_shared<GridInterpolator>("/scratch2/...");
```
(We will want a better way to do that later, but this is good for now.)

2024-01-31 14:24 UTC, mphoward commented on src/rpy_diffusive_flux.cc
> +                    ig += (M + M_ex) * rho_dmu;
This is not right for a few reasons:
* Doesn't the mobility in the file include the ideal part?
* The limits of integration need to be updated.
* The padding needs to also be updated accordingly.
* You need to clamp the values that are outside the bounds of your interpolant, or you will get an error.

Additionally, I recommend that for now you throw an error at the top of the function if there's more than 1 type and the diameter of that type is anything other than 1, as this will not currently work in that case. You can still leave all the for loops in place so that we don't lose that code though.

2024-01-31 17:44 UTC, mayukh33 commented on src/rpy_diffusive_flux.cc
> +                    ig += (M + M_ex) * rho_dmu;
Yes, it contains the ideal part as well. I will change that.

2024-02-02 21:54 UTC, mphoward requested changes
Please have a look at these comments and let me know when you have implemented the changes!

2024-02-02 21:54 UTC, mphoward commented on include/flyft/rpy_diffusive_flux.h
> +
```suggestion
```

2024-02-02 21:54 UTC, mphoward commented on src/grid_interpolator.cc
> +    indata >> x_ >> cutoff_ >> rho_ >> nx >> ny >> nz >> dx_ >> dy_ >> dz_;
Yes, here I think you are thinking these are going to be the bounds of your coordinates. You don't need to read them from a file, as you can compute them from the number of points and the spacing along each dimension. If your grid contains the end points (I think it does), then you should do like this:
```suggestion
    indata >> nx >> ny >> nz >> dx_ >> dy_ >> dz_;
    bounds_ = std::make_tuple((nx-1) * dx_, (ny-1) * dy_, (nz-1) * dz_);
```

2024-02-02 21:54 UTC, mphoward commented on include/flyft/grid_interpolator.h
> +        double rho_;
Why are these variables here? They seem specific to your application, not to the general interpolation problem. I think you want to declare a bounds variable instead:
```suggestion
        std::tuple<double, double, double> bounds_;
```
then compute it when you read the file.

2024-02-02 21:54 UTC, mphoward commented on src/grid_interpolator.cc
> +    return std::make_tuple(x_, dx_, rho_);
Then here:
```suggestion
    return bounds_;
```

2024-02-02 21:54 UTC, mphoward commented on src/rpy_diffusive_flux.cc
> +        }
If you are going to do this in the constructor, you don't need the `!mobility_` since we know it isn't initialized yet.
```suggestion
    mobility_ = std::make_shared<GridInterpolator>("/scratch2/mzk0148/projects/ddft_droplet/data/rdf_surrogate/m.dat"); 
```
You would only use that if you put this code in the `compute` method, which will be called multipled times.

2024-02-02 21:54 UTC, mphoward commented on src/rpy_diffusive_flux.cc
> +                const int ig_high = mesh->bin(x_int+cutoff);
This code should not use `x_int`, but instead the real `x` to set the bounds on y. You also don't need to do this all in one line if it's confusing to read.

2024-02-02 21:54 UTC, mphoward commented on src/rpy_diffusive_flux.cc
> +                const double cutoff = std::get<1>(g.getBounds())*d_ij;
You've already hard coded the diameter, so I don't think you should multiply by it here.
```suggestion
                const double cutoff = std::get<1>(g.getBounds());
```

2024-02-02 21:54 UTC, mphoward commented on src/rpy_diffusive_flux.cc
> +                    const double M = g(x_int, dx, phi);
Are you using `phi` or `rho` for the interpolation? I am confused because you have written `max_density` above.

2024-02-02 21:54 UTC, mphoward commented on src/rpy_diffusive_flux.cc
> +                    const double rho_x_int = std::min(rho_x, max_density);
Don't take the min here, do it once after you take the mean.

2024-02-02 21:54 UTC, mphoward commented on src/rpy_diffusive_flux.cc
> +    return mesh->asShape(del*0.5*(diameters_(type)+max_diameter));
This code is confusing because it allows for multiple types, but that is not currently supported. It will still work correctly if there's only one type and the diameter is 1.0, though, so we can leave it alone and edit later.

2024-02-02 21:54 UTC, mphoward commented on src/rpy_diffusive_flux.cc
> +        if(diameters_(i) > 1)
This should be like:
```suggestion
        if(diameters_(i) != 1)
```
since anything other than 1 is not allowed (including < 1). If it triggers an error because the value is close to (but not exactly) 1, we can write this check in a slightly different way.

2024-02-02 22:11 UTC, mayukh33 commented on src/rpy_diffusive_flux.cc
> +                    const double M = g(x_int, dx, phi);
It's using `phi` for interpolation right now. However, `max_density` is written based on density. I will change it to volume fraction from density.

2024-02-02 22:31 UTC, mayukh33 commented on src/grid_interpolator.cc
> +    indata >> x_ >> cutoff_ >> rho_ >> nx >> ny >> nz >> dx_ >> dy_ >> dz_;
Ohh okay! I will make the changes!

2024-02-05 14:59 UTC, mphoward commented on src/rpy_diffusive_flux.cc
> +    return mesh->asShape(cutoff*0.5*(diameters_(type)+max_diameter));
With the way the code is written, this should really just be:
```suggestion
    return mesh->asShape(cutoff);
```
and you don't need any of the for loop stuff.

2024-02-06 00:21 UTC, mayukh33 commented on src/rpy_diffusive_flux.cc
> +                const int ig_low = (x >= 1) ? (0): ig_low_near_center;
On the Python side, for generating the integral values, we have this code checking the lower limit of the integral:
```
if y < (0 if x >= 1 else 1 - x):
            continue
```
For the double integration calculation on the Python side, we did not deal with the lower limit calculations of the integral. I think we tried doing the calculation mentioned above on the Python side, but we were triggering the assert statement that `r>=1`

2024-02-07 17:38 UTC, mphoward requested changes
Nice work! Here are a couple minor comments, and then one about updating the `m.dat` file to use density before we try running calculations with this.

2024-02-07 17:38 UTC, mphoward commented on include/flyft/grid_interpolator.h
> +        std::tuple<double, double, double> getLowerBounds() const ;
```suggestion
        std::tuple<double, double, double> getLowerBounds() const;
```

2024-02-07 17:38 UTC, mphoward commented on include/flyft/rpy_diffusive_flux.h
> +        int determineBufferShape(std::shared_ptr<State> state, const std::string&) override;
Revert this change. Although it is not strictly required by C++, I prefer to include the names of the variables in the header for readability.
```suggestion
        int determineBufferShape(std::shared_ptr<State> state, const std::string& type) override;
```

2024-02-07 17:38 UTC, mphoward commented on src/grid_interpolator.cc
> +    indata >> x_low >> x_high >> y_low >> y_high >> z_low >> z_high >>nx >> ny >> nz;
```suggestion
    indata >> x_low >> x_high >> y_low >> y_high >> z_low >> z_high >> nx >> ny >> nz;
```

2024-02-07 17:38 UTC, mphoward commented on src/rpy_diffusive_flux.cc
> +#include <algorithm>
I can't remember everything that's in this header, but what are you using that needs it?

2024-02-07 17:38 UTC, mphoward commented on src/rpy_diffusive_flux.cc
> +    const double cutoff = std::get<1>(g.getUpperBounds());
You should add a sanity check here that this lower bound of this dimension is the same as `-cutoff`, or it will lead to undefined behavior later.

2024-02-07 17:38 UTC, mphoward commented on src/rpy_diffusive_flux.cc
> +                const double x_low = std::max(x - cutoff, (x >= 1) ? 0 : d_ij-x);
Isn't this for y?
```suggestion
                const double y_low = std::max(x - cutoff, (x >= 1) ? 0 : d_ij-x); 
```

2024-02-07 17:38 UTC, mphoward commented on src/rpy_diffusive_flux.cc
> +int RPYDiffusiveFlux::determineBufferShape(std::shared_ptr<State> state, const std::string&)
I prefer to comment out the variable name like this if it is unused:
```suggestion
int RPYDiffusiveFlux::determineBufferShape(std::shared_ptr<State> state, const std::string& /* type */)
```

2024-02-07 17:38 UTC, mphoward commented on src/rpy_diffusive_flux.cc
> +                    const double M = g(x_int, dx, mean_phi);
I think at this point it makes sense for us to update our Python script to use density rather than volume fraction, so we can remove `mean_phi`. It shouldn't be too much changes!

2024-02-09 14:32 UTC, mphoward requested changes
Much better! Here are a few small comments.

2024-02-09 14:32 UTC, mphoward commented on src/grid_interpolator.cc
> +    const int bin_x = (std::abs(std::floor(fx) - (std::get<0>(bounds) - 1)) == 0) ? std::floor(fx) - 1 : std::floor(fx);
You are on the right track, but I don't think this is how I would do this. Instead, I would probably do something like:
```suggestion
   int bin_x = std::floor(fx);
   if(fx == std::get<0>(bounds) && x == std::get<0>(upper_bounds_))
       {
       --bin_x;
       }
```
The second condition could be relaxed to an "is close" type tolerance if we find this is not working.

2024-02-09 14:32 UTC, mphoward commented on src/grid_interpolator.cc
>      #ifndef NDEBUG
You can remove this if you are now using `bounds` above for something other than debugging. The `assert` statements internally will check this `ifndef`

2024-02-09 14:32 UTC, mphoward commented on src/grid_interpolator.cc
> +    assert(bin_z >= 0 && bin_z < std::get<2>(bounds) - 1);
Did you try adding `assert(false);` just to make sure these are being run?

2024-02-09 14:53 UTC, mayukh33 commented on src/grid_interpolator.cc
> +    assert(bin_z >= 0 && bin_z < std::get<2>(bounds) - 1);
Yes! I looked at it and it was not in the correct mode. I recompiled it with the Debug mode on.

2024-02-09 19:17 UTC, mphoward reviewed
I have a couple minor cosmetic things, but then this looks like it is good to go! Have you tried running this with unit tests?

2024-02-09 19:17 UTC, mphoward commented on include/flyft/rpy_diffusive_flux.h
> +
```suggestion
```

2024-02-09 19:17 UTC, mphoward commented on src/grid_interpolator.cc
> +       }
For readability, I would interleave these like this and also add a comment on the first one about why we decrement:
```suggestion

    const auto bounds = n_.getBounds();
    // x
    int bin_x = std::floor(fx);
    if(fx == std::get<0>(bounds) - 1 && x == std::get<0>(upper_bounds_))
       {
       /* for points exactly on the upper boundary, decrease by 1 to put it in
          bin below. this makes sure we only access bins within the bounds
          during interpolation
       */
       --bin_x;
       }
    // y
    int bin_y = std::floor(fy);
    if(fy == std::get<1>(bounds) - 1 && x == std::get<1>(upper_bounds_))
       {
       --bin_y;
       }
    // z
    int bin_z = std::floor(fz);
    if(fz == std::get<2>(bounds) - 1 && x == std::get<2>(upper_bounds_))
       {
       --bin_z;
       }
```

2024-02-09 19:17 UTC, mphoward commented on src/rpy_diffusive_flux.cc
> +    const double max_density = std::get<2>(g.getUpperBounds());
For readability, I would read this at the same time as the other things, then do the error check
```suggestion
    const double max_density = std::get<2>(g.getUpperBounds());

    if(std::get<1>(g.getLowerBounds()) != -cutoff)
        {
        throw std::invalid_argument("Cutoff bounds for integration are not valid");
        }

```

2024-02-09 19:31 UTC, mayukh33 commented
> I have a couple minor cosmetic things, but then this looks like it is good to go! Have you tried running this with unit tests?

I am running the Python script to generate the flux values for the comparison. However, I made a mistake in the last run, which took around 4 hours to generate the values. I am regenerating the values and will let you know what I find! I have added the rho(x) and rho(y) terms into the integral, and the density field is `(0.8/R) * x`

2024-02-09 22:02 UTC, mphoward reviewed
There are two minor things open to fix, both otherwise this looks good! I am not going to approve/merge it because we still have the file path hard coded in here, but I think we are good to finalize testing on it and start to try it out.

2024-02-09 22:02 UTC, mphoward commented on src/rpy_diffusive_flux.cc
> +                const double y_low = std::max(x - cutoff, (x >= 1) ? 0 : d_ij-x);
Either make these both one, or both `d_ij`. Probably `d_ij` will be easier to generalize in future!
```suggestion
                const double y_low = std::max(x - cutoff, (x >= d_ij) ? 0 : d_ij-x); 
```

2024-02-09 22:03 UTC, mphoward commented
> I am running the Python script to generate the flux values for the comparison. However, I made a mistake in the last run, which took around 4 hours to generate the values.

If it's taking a long time to generate the reference values, you could limit yourself to only certain x values. It isn't necessary to check every single one, you could skip every couple.

2025-01-30 20:21 UTC, mphoward approved these changes
Thank you!

2025-01-30 20:22 UTC, merged